[package]
name = "example_contracts_impl"
version = "0.1.0"
authors = [""]
edition = "2018"

[lib]
proc_macro = true
test = false
doctest = false

[dependencies]
quote = "0.6"
proc-macro2 = "0.4.30"

[dependencies.syn]
version = "0.15"
features = [ "full", "parsing" ]
